### ISSUE TITLE
implement fit_msm

### ISSUE THREAD

**Issue by gravesti** [Causal-LDA/TrialEmulation#163]
Depends on #161 
- [x] Define new generic `fit_msm(object, ...)`
  - [x] options for weighting?  see `trial_msm()` maybe truncation or no weighting
- [x] Define new method for trial_sequence class
  - [x] check if `@outcome_data` is empty, if so read_expanded_data
  - [x] if datastore is empty, error and ask user to expand data
  - [x] if `is(@outcome_model, "te_outcome_unset")` give error: run set outcome model
  - [x] fit_outcome_model(object, data, formula, weights) and save result to @te_outcome_model@fitted
    - [x] object is model_fitter
    - [x] data is @outcome_data
    - [x] formula is from outcome_model@formula
    - [x] weights need to calculated, eg truncated or multiplied with sample weights, and added to data.table
  - [x] add tests
  - [ ] add docs

**Comment by darkgoldenrod-cherry** [comment]
changed read_expanded_data method for te_datastore_duckdb-class
- subsetting now happens in the DBI query instead of afterwards, depends now on translate_to_sql

created load_expanded_data generic and method for trial_sequence-class
- copied sample_controls, added if statement to read_expanded_data if p_control = NULL (default)
- adapted documentation
- sample_controls still exists unchanged

created fit_msm generic and method for trial_sequence-class
- copied the weighting options from trial_msm function
- depends currently on load_expanded_data
- formula in my example code returns error

- [ ] tests for load_expanded_data
- [ ] documentation for fit_msm
- [ ] tests for fit_msm
